apiVersion: v1
kind: Service
metadata:
  name: deepseek-ollama-service
spec:
  selector:
    app: deepseek-ollama
  ports:
    - protocol: TCP
      port: 8080        # Expose this port outside the cluster
      targetPort: 11434  # Forward traffic to this port inside the container
  type: ClusterIP
